name:                zlibVersion
version:             0.2.0.0
github:              "mpilgrem/zlibVersion"
license:             BSD3
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2020 and 2021 Mike Pilgrem"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mpilgrem/zlibVersion#readme>

ghc-options:
- -Weverything
- -Wno-implicit-prelude

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- optparse-applicative
- portable-lines
- typed-process

# In order for `stack build` to work, a copy of zlib1.dll must be able to be
# located. If `stack build` does not work, add a copy of zlib1.dll to the
# folder identified below.
extra-lib-dirs: lib
extra-libraries: "zlib1"

executables:
  zlibVersion:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
